Fix check/download/etc for macos

diff --git a/dist/macos b/dist/macos
--- a/dist/macos
+++ b/dist/macos
@@ -6,7 +6,7 @@ GUEST="macos"
 IMAGE_TYPE="img"
 
 function dist_releases() {
-    echo high-sierra mojave catalina big-sur monterey ventura sonoma
+    echo mojave catalina big-sur monterey ventura sonoma
 }
 
 function generate_id() {
@@ -19,12 +19,12 @@ function generate_id() {
     echo "${macRecoveryID}"
 }
 
-function dist_image_get() {
-    local BOARD_ID=""
-    local CWD=""
-    local CHUNKCHECK=""
-    local MLB="00000000000000000"
+function get_info() {
+    local appleSession=""
+    local info=""
     local OS_TYPE="default"
+    local BOARD_ID=""
+    local MLB="00000000000000000"
 
     case ${RELEASE} in
       lion)           #10.7
@@ -66,6 +66,29 @@ function dist_image_get() {
         exit 1;;
     esac
 
+    appleSession=$(curl -v -H "Host: osrecovery.apple.com" \
+                           -H "Connection: close" \
+                           -A "InternetRecovery/1.0" \
+                           http://osrecovery.apple.com/ 2>&1 | tr ';' '\n' | awk -F'session=|;' '{print $2}' | grep 1)
+    info=$(curl -s -X POST -H "Host: osrecovery.apple.com" \
+                           -H "Connection: close" \
+                           -A "InternetRecovery/1.0" \
+                           -b "session=\"${appleSession}\"" \
+                           -H "Content-Type: text/plain" \
+                           -d $'cid='$(generate_id 16)$'\nsn='${MLB}$'\nbid='${BOARD_ID}$'\nk='$(generate_id 64)$'\nfg='$(generate_id 64)$'\nos='${OS_TYPE} \
+                           http://osrecovery.apple.com/InstallationPayload/RecoveryImage | tr ' ' '\n')
+    echo "${info}"
+}
+
+function dist_image_get() {
+    local downloadLink=""
+    local downloadSession=""
+    local chunkListLink=""
+    local chunkListSession=""
+    local info=""
+    local CWD=""
+    local CHUNKCHECK=""
+
     CWD="$(dirname "${0}")"
     if [ -x "${CWD}/chunkcheck" ]; then
         CHUNKCHECK="${CWD}/chunkcheck"
@@ -73,69 +96,30 @@ function dist_image_get() {
         CHUNKCHECK="$(command -v chunkcheck)"
     fi
 
-    if [ -z "${CHUNKCHECK}" ]; then
-        # read -p "ERROR! Can not find chunkcheck. Will not be able to verify image. Proceed anyway?" skipVerification
-        # if [ "${skipVerification,,}" != "y" ] && [ "${skipVerification,,}" != "yes" ]; then
-        #     exit 1
-        # fi
-        # echo 'Skipping verification' && skipVerification="true"
-        skipVerification="true"
-    fi
-
-    OpenCore_qcow2="https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2"
-    OVMF_CODE="https://github.com/kholia/OSX-KVM/raw/master/OVMF_CODE.fd"
-    OVMF_VARS="https://github.com/kholia/OSX-KVM/raw/master/OVMF_VARS-1920x1080.fd"
-
-    local appleSession=$(curl -v -H "Host: osrecovery.apple.com" -H "Connection: close" -A "InternetRecovery/1.0" http://osrecovery.apple.com/ 2>&1 | tr ';' '\n' | awk -F'session=|;' '{print $2}' | grep 1)
-    local info=$(curl -s -X POST -H "Host: osrecovery.apple.com" -H "Connection: close" -A "InternetRecovery/1.0" -b "session=\"${appleSession}\"" -H "Content-Type: text/plain"\
-    -d $'cid='$(generate_id 16)$'\nsn='${MLB}$'\nbid='${BOARD_ID}$'\nk='$(generate_id 64)$'\nfg='$(generate_id 64)$'\nos='${OS_TYPE} \
-    http://osrecovery.apple.com/InstallationPayload/RecoveryImage | tr ' ' '\n')
-    local downloadLink=$(echo "$info" | grep 'oscdn' | grep 'dmg')
-    local downloadSession=$(echo "$info" | grep 'expires' | grep 'dmg')
-    local chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
-    local chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
+    info=$(get_info)
+    downloadLink=$(echo "$info" | grep 'oscdn' | grep 'dmg')
+    downloadSession=$(echo "$info" | grep 'expires' | grep 'dmg')
+    chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
+    chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
     
-    # if [ "${OPERATION}" == "show" ]; then
-    #     test_result "${OS}" "${RELEASE}" "" "${downloadLink}"
-    #     exit 0
-    # elif [ "${OPERATION}" == "test" ]; then
-    #     local CHECK=$(web_check "${downloadLink}" --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}" && echo 'PASS' || echo 'FAIL')
-    #     test_result "${OS}" "${RELEASE}" "" "${downloadLink}" "${CHECK}"
-    #     exit 0
-    # elif [ "${OPERATION}" == "download" ]; then
-    #     echo "Downloading macOS ${RELEASE} from ${downloadLink}"
-    #     web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
-    #     web_get "${chunkListLink}" "${VM_PATH}" RecoveryImage.chunklist --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
-    #     VM_PATH="$(pwd)"
-    # else
-        # echo "Downloading macOS firmware"
-        web_get "${OpenCore_qcow2}" "${VM_PATH}"
-        web_get "${OVMF_CODE}" "${VM_PATH}"
-        if [ ! -e "${VM_PATH}/OVMF_VARS-1920x1080.fd" ]; then
-            web_get "${OVMF_VARS}" "${VM_PATH}"
-        fi
-
+    if [ ! -z "${OPERATION}" ]; then
+        dist_image_test
+        exit 0
+    else 
         if [ ! -e "${VM_PATH}/RecoveryImage.chunklist" ]; then
-            # echo "Downloading macOS ${RELEASE} from ${downloadLink}"
+            echo "Downloading macOS (${RELEASE^}) RecoveryImage" >&2
+            echo " - URL: ${downloadLink}" >&2
             web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
             web_get "${chunkListLink}" "${VM_PATH}" RecoveryImage.chunklist --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
+            if ! "${CHUNKCHECK}" "${VM_PATH}" 2> /dev/null; then
+                echo " - WARNING! Verification failed, continuing anyway" >&2
+            else
+                echo " - Verification passed" >&2
+            fi
         fi
-    # fi
-    
-    # if [ "${skipVerification}" != "true" ]; then
-    #     if ! "${CHUNKCHECK}" "${VM_PATH}" 2> /dev/null; then
-    #         echo "Verification failed."
-    #     else
-    #         echo "Verified macOS ${RELEASE} image using chunklist."
-    #     fi
-    # else
-    #     echo "Skipping verification of image."
-    # fi
 
-    # Dumb hack
-    cp "${VM_PATH}/RecoveryImage.dmg" "${VM_PATH}/RecoveryImage.img"
-
-    echo "file://${PWD}/${VM_PATH}/RecoveryImage.img"
+    fi
+    echo "${downloadLink%/BaseSystem.dmg}/RecoveryImage.dmg"
 }
 
 function dist_vm_option_tweak() {
@@ -146,13 +130,51 @@ function dist_vm_option_tweak() {
     fi
 }
 
-function dist_image_post_get() {
-    rm "${VM_PATH}/RecoveryImage.img"
-    if [ -e "${VM_PATH}/RecoveryImage.dmg" ] && [ ! -e "${VM_PATH}/RecoveryImage.img" ]; then
-        # echo "Converting RecoveryImage..."
-        qemu-img convert "${VM_PATH}/RecoveryImage.dmg" -O raw "${VM_PATH}/RecoveryImage.img" 2>/dev/null
+function dist_image_pre_get() {
+    if [ ! -e "${VM_PATH}/OpenCore.qcow2" ]; then
+        echo "Downloading OpenCore & UEFI firmware:"
+        web_get "https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2" "${VM_PATH}"
+        web_get "https://github.com/kholia/OSX-KVM/raw/master/OVMF_CODE.fd" "${VM_PATH}"
+        if [ ! -e "${VM_PATH}/OVMF_VARS-1920x1080.fd" ]; then
+            web_get "https://github.com/kholia/OSX-KVM/raw/master/OVMF_VARS-1920x1080.fd" "${VM_PATH}"
+        fi
     fi
-    rm -f "${VM_PATH}/RecoveryImage.dmg" "${VM_PATH}/RecoveryImage.chunklist"
+}
+
+function dist_image_post_get() {
+    if [ -e "${VM_PATH}/RecoveryImage.dmg" ] && [ ! -e "${VM_PATH}/RecoveryImage.img" ]; then
+        echo " - Converting RecoveryImage.dmg"
+        ${QEMU_IMG} convert "${VM_PATH}/RecoveryImage.dmg" -O raw "${VM_PATH}/RecoveryImage.img" 2>/dev/null
+        echo " - RecoveryImage.img is ready."
+    fi
+    rm "${VM_PATH}/RecoveryImage.dmg" "${VM_PATH}/RecoveryImage.chunklist"
+    ISO="(ls -1 "${VM_PATH}/"*.img | cut -d'/' -f2)"
+}
+
+function dist_image_test() {
+    local info=""
+    local downloadLink=""
+    local downloadSession=""
+    local chunkListLink=""
+    local chunkListSession=""
+
+    info=$(get_info)
+    downloadLink=$(echo "$info" | grep 'oscdn' | grep 'dmg')
+    downloadSession=$(echo "$info" | grep 'expires' | grep 'dmg')
+    chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
+    chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
+
+    if [ "${OPERATION}" == "show" ]; then
+        test_result "${OS}" "${RELEASE}" "" "${downloadLink}"
+    elif [ "${OPERATION}" == "test" ]; then
+        CHECK=$(web_check "${downloadLink}" --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie:AssetToken=${downloadSession}" && echo 'PASS' || echo 'FAIL')
+        test_result "${OS}" "${RELEASE}" "" "${downloadLink}" "${CHECK}"
+    elif [ "${OPERATION}" == "download" ]; then
+        echo "Downloading macOS ${RELEASE} from ${downloadLink}" >&2
+        web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
+        web_get "${chunkListLink}" "${VM_PATH}" RecoveryImage.chunklist --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
+        VM_PATH="$(pwd)"
+    fi
 }
 
 # vim:tabstop=4:shiftwidth=4:expandtab
